# -*- coding: utf-8 -*-
"""python_intro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHV3jSOQ2aYA3gb_UvxIiPgQRJ6unFZ0

**Variables**
"""

students_count=30
rating=4.99
is_published=False
course_name='Python Basics'
COURSE_NAME="Statistics Learning"

print(students_count)
print(rating)
print(is_published)
print(course_name)

"""**Strings**"""

course= 'Python Programming'
print(len(course))
print(course[0])
print(course[-1])
print(course[0:3])
print(course[3:])

first='Subhajit'
last='Dutta'
full=first+' '+last
print(full)
# Formated String
full=f'{first} {last}'
print(full)

"""```course``` a python string object of the built-in class ```str```. Objects in Python have attributes and methods. Attributes are like properties (e.g., the length of the string). Methods are like actions we can do with the object (e.g. changing all letters to uppercase)."""

course='python programming'
print(course.upper())
print(course.find('pro'))
print(course.replace('p','j'))

"""**Numbers**"""

print(10/3)
print(10//3)    # returns the integer part
print(10%3)     # returns the remainder
print(10**3)    # returns the
print(round(2.9))
print(abs(-2.9))

import math
print(math.ceil(2.2))

"""Input Statement"""

name=input('Enter your name:')
age=input('Enter your age: ')
print("Hello "+name+'! You are '+age)

"""**Lists**"""

lucky_numbers=[4,8,15,16,23,42]
friends=['kevin','karen','Jim']
print(friends[0])

friends.extend(lucky_numbers)
print(friends)

friends.append('creed')
print(friends)

friends.insert(1,'kelly')
print(friends)

friends.remove('Jim')

print(friends.index('kevin'))

friends=['kevin','karen','Jim']
friends.sort()
print(friends)

friends.reverse()

friends.clear()

"""**Functions**"""

def cube(num):
  return num*num*num

result=cube(3)
print(result)

"""**if else statement**"""

is_male=False
is_tall=False

if is_male and is_tall:
  print("You are a tall male")
else:
  print('You are either not male or not tall')

def max_num(num1,num2,num3):
  if num1>=num2 and num1>=num3:
    return num1
  elif num2>=num1 and num2>=num3:
    return num2
  else:
    return num3

max_num(3,40,5)

"""**While loop**"""

i=1
while i<=10:
  print(i)
  i+=1

"""**For loop**"""

for letter in 'Statistics Learning':
  print(letter)

"""**try except statement**"""

try:
  number= 10/0
  number=int(input("Enter a number:"))
  print(number)
except ZeroDivisionError as err:
  print(err)
except ValueError:
  print('Invalid input')

"""**Reading and writing in files**"""

list_file=open("speakers_syllabus.txt","a")
# print(cnae_file.read())
list_file.write("\nDr. Minerva Mukhopadhyay: Basics of Linear Algebra, Introduction to Bayesian Methods")
list_file.write("\nDr. Debraj Das: Probability Distributions, Some Useful Inequalities, Concentration Inequalities, Metrics and Divergences Between Probability Distributions")
list_file.write("\nDr. Subhajit Dutta: Introduction to Statistical Learning, An Introduction to R and Python")
list_file.write("\nDr. Soham Sarkar: Primer on Functional Analysis and Probability on Hilbert Spaces, Introduction to Functional Data")
list_file.write("\nDr. Anirvan Chakraborty: Classification of Functional Data")
list_file.close()

"""**modules** : A module is a .py file that contains python codes-usually functions, classes, variables that can be used in other programs by importing it."""

# /content/speakers_syllabus.txt
# /content/sample_data/mnist_test.csv

import mymath

print(mymath.add(3,5))
print(mymath.divide(100,10))

"""More existing python modules are there: https://docs.python.org/3/py-modindex.html#cap-n

There are a lot of third party modules also. You can install them in your system: go to terminal/command prompt then type these commands
```pip install module_name```

( if pip is not installed in your system, then install pip using::

for windows: ```python get-pip.py```

for Linux: ```sudo apt install python3-pip```        )

Google Colab has already a lot of modules. So you don't have to install them here. Just import the modules and use them.

**numpy module**
"""

import numpy as np

a=np.array([1,2,3])
print(a)
b= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(b)

a = np.array([1, 2, 3], dtype=np.float32)
print(a.dtype)

a = np.array([1.5, 2.8, 3.3])
b = a.astype(np.int32)  # Truncates decimals
print(b)

print(a.ndim)
print(a.shape)
print(np.shape(a))

print(b.ndim)
print(b.shape)
print(np.shape(b))

print(b[1,5])
print(b[0,:])
print(b[1,2:5])

# Initialize different types of arrays
c= np.zeros((2,3))
print(c)

d=np.ones((3,3))
print(d)

e=np.empty((2,2))
print(e)

f=np.random.rand(3,3)
print(f)

g=np.identity(3)
print(g)

a=np.ones((2,3))
b=np.full((3,2),2)

np.matmul(a,b)

a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
b=a.reshape((4,2))
print(b)

"""array concatenation"""

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenate along axis 0 (vertically)
result = np.concatenate((a, b), axis=0)  # a and b should have same number of columns
print(result)

# Or we can do vstack also to stack arrays vertically
result2= np.vstack((a,b))
print(result2)

a = np.array([[1], [2]])
b = np.array([[3], [4]])

result= np.concatenate((a, b), axis=1)  # a and b should have same number of rows
print(result)

# Or we can do hstack also to stack arrays horizontally
result2= np.hstack((a,b))
print(result2)

a = np.array([1, 2])
b = np.array([3, 4])

result = np.stack((a, b), axis=0)  # Shape (2, 2)
result2 = np.stack((a, b), axis=1) # Shape (2, 2)
print(result)
print(result2)

# 3D array
a = np.random.rand(2, 3, 4)  # Shape: (2, 3, 4)
b = np.random.rand(2, 3, 4)  # Shape: (2, 3, 4)

# Concatenate along axis=0
res1 = np.concatenate((a, b), axis=0)
print(res1.shape)

# Concatenate along axis=1
res2 = np.concatenate((a, b), axis=1)
print(res2.shape)

# Concatenate along axis=2
res2 = np.concatenate((a, b), axis=2)
print(res2.shape)

# add new axis before concatenation
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x.shape)

# Convert to 2D
x2 = x[:, np.newaxis]
y2 = y[:, np.newaxis]
print(x2.shape)

res = np.concatenate((x2, y2), axis=1)
print(res.shape)

# repeat many times
a = np.array([1, 2])
res = np.tile(a, (3, 1))
print(res)

# Repeat elements along a specific axis
res2 = np.repeat(a[np.newaxis, :], 3, axis=0)
print(res2)

# flatten function
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a.shape)

b=a.flatten()
print(b.shape)
print(b)

"""Importing .txt and .csv file using numpy"""

data = np.loadtxt('example_data.csv', delimiter=',')
print(data.shape)
print(data)

"""Plotting in python"""

import matplotlib.pyplot as plt

x=np.random.random(50)*100
y=np.random.random(50)*100

#scatter plot
plt.scatter(x,y, c='red', marker='*',s=150)

#plt.show

years=[2012+ x for x in range(10)]
print(years)

weights=[80,83,84,79,88,70,90,89,75,71]
# line plot
plt.plot(years,weights)
plt.title('Plot of weights')
plt.xlabel('Years')
plt.ylabel('Weights')

import pandas as pd

# In this "sample_data.csv" file there are 5188 different time series trials each belonging
# to one of the 6 classes. Last column of the data is the class_labels. The time-
# series is recorded for 500 mili second with a sampling rate 64
data=pd.read_csv('example_data.csv',header=None)

#member=data.iloc[:,-1]
data=data.to_numpy()
print(data.shape)
member= data[:,-1]
print(member.shape)

data=data[:,:-1]
print(data.shape)

cl1_data=data[member==1,:]
cl2_data= data[member==2,:]
cl3_data= data[member==3,:]
cl4_data= data[member==4,:]
cl5_data= data[member==5,:]
cl6_data= data[member==6,:]

cl1 = cl1_data.mean(axis=0)
cl2 = cl2_data.mean(axis=0)
cl3 = cl3_data.mean(axis=0)
cl4 = cl4_data.mean(axis=0)
cl5 = cl5_data.mean(axis=0)
cl6 = cl6_data.mean(axis=0)
print(cl6.shape)

x = np.linspace(0,500,32)
# plot the time-series based on their class label
plt.plot(x,cl1,'r',lw=2,label='class1')
plt.plot(x,cl2,'g',lw=2,label='class2')
plt.plot(x,cl3,'b',lw=2,label='class3')
plt.plot(x,cl4,'y',lw=2,label='class4')
plt.plot(x,cl5,'k',lw=2,label='class5')
plt.plot(x,cl6,'m',lw=2,label='class6')
plt.legend(fontsize=10)
plt.title('Plot of 6 different classes',fontsize=25)
plt.xlabel('Time (ms)',fontsize=20)
plt.ylabel('Amplitude',fontsize=20)
plt.xticks(np.arange(0, 501, 100),fontsize=15)
plt.yticks(fontsize=15)
plt.grid()

# To save the figure
plt.savefig('time_series_6_class.pdf', bbox_inches='tight')
# plt.show()

x=['Math','Stat','CS','PHY','BIO','CHEM']
y=[25,20,30,35,50,40]

# bar plot
plt.bar(x,y,color='b')

ages=np.random.normal(20,1.5,1000)

#print(ages)

# Hisogram
plt.hist(ages,bins=20)

x= np.random.normal(172,8,300)

# Boxplot
plt.boxplot(x)

## Subplots
x=np.arange(100)

fig,axs= plt.subplots(2,2)

axs[0,0].plot(x,np.sin(x))
axs[0,0].set_title('Sine Wave')

axs[0,1].plot(x,np.cos(x))
axs[0,1].set_title('Cosine Wave')

axs[1,0].plot(x,np.tan(x))
axs[1,0].set_title('Tangent Wave')

axs[1,1].plot(x,np.log(x))
axs[1,1].set_title('Log Function')
axs[1,1].set_xlabel('X-axis')
axs[1,1].set_ylabel('Y-axis')

fig.suptitle('Four subplots')

# 3D plotting
ax=plt.axes(projection='3d')

x =np.random.random(100)
y =np.random.random(100)
z =np.random.random(100)

ax.scatter(x,y,z)
ax.set_title('3D Scatter Plot')
ax.set_xlabel('X-axis')
ax.set_ylabel('Y-axis')
ax.set_zlabel('Z-axis')

# plt.show()

# To interact with 3D plots in Google Colab or any Jupyter-based environment
# import plotly.express as px
# fig = px.scatter_3d(x=x, y=y, z=z, labels={'x': 'X-axis', 'y': 'Y-axis', 'z': 'Z-axis'})
# fig.show()

ax=plt.axes(projection='3d')

x =np.arange(0,50,0.1)
y =np.sin(x)
z =np.cos(x)

ax.plot(x,y,z)

# To interact with 3D plots in Google Colab or any Jupyter-based environment
# import plotly.graph_objects as go
# fig = go.Figure(data=[go.Scatter3d(
#     x=x, y=y, z=z,
#     mode='lines',
#     line=dict(color='blue', width=4)
# )])
# fig.update_layout(
#     title='Interactive 3D Line Plot',
#     scene=dict(xaxis_title='X',yaxis_title='sin(x)',zaxis_title='cos(x)'))

# fig.show()

ax=plt.axes(projection='3d')

x =np.arange(-5,5,0.1)
y =np.arange(-5,5,0.1)
x,y=np.meshgrid(x,y)
z=np.sin(x)+np.cos(y)

ax.plot_surface(x,y,z)

# To interact with 3D plots in Google Colab or any Jupyter-based environment
# import plotly.graph_objects as go
# fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
# fig.update_layout(title='3D Surface Plot', scene=dict(
#                     xaxis_title='X',
#                     yaxis_title='Y',
#                     zaxis_title='Z'))

"""Making the plot animated"""

import random
from IPython.display import clear_output

heads_tails= [0,0]
for _ in range(100):
  heads_tails[random.randint(0,1)] += 1

  # Clear previous plot
  clear_output(wait=True)

  plt.bar(['Heads','Tails'],heads_tails,color=['r','g'])
  plt.pause(0.001)

"""```scipy``` module"""

from scipy import stats

# t-test
group1 = np.random.normal(10, 2, 100)
group2 = np.random.normal(12, 2, 100)

# independent t-test
t_stat, p_val = stats.ttest_ind(group1, group2)
print("t-statistic:", t_stat, "p-value:", p_val)

# paired t-test
t_stat, p_val = stats.ttest_rel(group1, group2)
print("t-statistic:", t_stat, "p-value:", p_val)

from scipy.io import loadmat
# import .mat (matlab files) files using scipy module
my_data = loadmat('example_mat_file.mat')

# available variables names
print(my_data.keys())

# access a variable
data = my_data['data']
member= my_data['member']

print(data.shape)
print(member.shape)

"""Doing PCA on iris data"""

from sklearn.decomposition import PCA
from sklearn.datasets import load_iris

iris = load_iris()
X = iris.data
y = iris.target
feature_names = iris.feature_names

X_selected = X[:, :2]

plt.figure(figsize=(14, 6))
# Plot for original features (sepal length vs sepal width)
plt.subplot(1, 2, 1)
plt.scatter(X_selected[:, 0], X_selected[:, 1], c=y, cmap='viridis')
plt.title('Original Features (Sepal Length vs Sepal Width)')
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')

# Perform PCA to reduce to 2 components
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Plot for PCA components
plt.subplot(1, 2, 2)
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y, cmap='viridis')
plt.title('PCA of Iris Dataset')
plt.xlabel('First Principal Component')
plt.ylabel('Second Principal Component')

plt.tight_layout()
plt.show()

"""**Some questions to try yourself**
1. Write a for loop to print the first 10 Fibonacci numbers. (F(n+1)=F(n)+F(n-1))
2. Generate a list of 100 random numbers and calculate the 25th, 50th, and 75th percentiles using numpy.
(Hint: Use ```np.percentile()``` function of ```numpy``` module.)
3. Generate synthetic linear data (y = 2x + noise), fit a linear regression model, and plot the regression line.
(Hint: Import ```LinearRegression``` function from ```sklearn.linear_model``` module. Use ```model=LinearRegression()``` to initialize and ```model.fit(X,Y)``` to fit the model and ```model.predict(X)``` to predict.
4. Apply PCA to the Iris dataset and plot the first two principal components. Explain how much variance is explained by the first two components.
5. Simulate rolling two dice 1000 times and plot the distribution of the sum of the two dice.
(Hint: use ```np.random.randint(l, u, n)``` to simulate dice roll.)
6. Create a pandas DataFrame with student names, marks, and subjects and filter students with marks > 70 and calculate the average mark.

"""